teams:
- display_names:
  - Vitality
  - Team Vitality
  team_id: vitality
  source_refs:
    cs2settings:
      team_slug: vitality
    prosettings: {}
    proconfig: {}
- display_names:
  - Spirit
  - Team Spirit
  team_id: team-spirit
  source_refs:
    cs2settings:
      team_slug: spirit
    prosettings: {}
    proconfig: {}
- display_names:
  - NAVI
  - Natus Vincere
  team_id: natus-vincere
  source_refs:
    cs2settings:
      team_slug: navi
    prosettings: {}
    proconfig: {}
- display_names:
  - Falcons
  - Team Falcons
  team_id: falcons
  source_refs:
    cs2settings:
      team_slug: falcons
    prosettings: {}
    proconfig: {}
- display_names:
  - FURIA
  team_id: furia
  source_refs:
    cs2settings:
      team_slug: furia
    prosettings: {}
    proconfig: {}
- display_names:
  - The MongolZ
  - The Mongolz
  team_id: the-mongolz
  source_refs:
    cs2settings:
      team_slug: the-mongolz
    prosettings: {}
    proconfig: {}
- display_names:
  - Astralis
  team_id: astralis
  source_refs:
    cs2settings:
      team_slug: astralis
    prosettings: {}
    proconfig: {}
- display_names:
  - MOUZ
  team_id: mouz
  source_refs:
    cs2settings:
      team_slug: mouz
    prosettings: {}
    proconfig: {}
- display_names:
  - G2
  - G2 Esports
  team_id: g2
  source_refs:
    cs2settings:
      team_slug: g2
    prosettings: {}
    proconfig: {}
- display_names:
  - FaZe
  - FaZe Clan
  team_id: faze
  source_refs:
    cs2settings:
      team_slug: faze
    prosettings: {}
    proconfig: {}
- display_names:
  - GamerLegion
  team_id: gamerlegion
  source_refs:
    cs2settings:
      team_slug: gamerlegion
    prosettings: {}
    proconfig: {}
- display_names:
  - 3DMAX
  team_id: 3dmax
  source_refs:
    cs2settings:
      team_slug: 3dmax
    prosettings: {}
    proconfig: {}
- display_names:
  - PARIVISION
  team_id: parivision
  source_refs:
    cs2settings:
      team_slug: parivision
    prosettings: {}
    proconfig: {}
- display_names:
  - Heroic
  - HEROIC
  team_id: heroic
  source_refs:
    cs2settings:
      team_slug: heroic
    prosettings: {}
    proconfig: {}
- display_names:
  - Team Liquid
  - Liquid
  team_id: liquid
  source_refs:
    cs2settings:
      team_slug: liquid
    prosettings: {}
    proconfig: {}
- display_names:
  - FUT
  team_id: fut
  source_refs:
    cs2settings:
      team_slug: fut
    prosettings: {}
    proconfig: {}
- display_names:
  - Monte
  team_id: monte
  source_refs:
    cs2settings:
      team_slug: monte
    prosettings: {}
    proconfig: {}
- display_names:
  - B8
  team_id: b8
  source_refs:
    cs2settings:
      team_slug: b8
    prosettings: {}
    proconfig: {}
- display_names:
  - BetBoom
  team_id: betboom
  source_refs:
    cs2settings:
      team_slug: betboom
    prosettings: {}
    proconfig: {}
- display_names:
  - MIBR
  team_id: mibr
  source_refs:
    cs2settings:
      team_slug: mibr
    prosettings: {}
    proconfig: {}
- display_names:
  - 9z
  team_id: 9z
  source_refs:
    cs2settings:
      team_slug: 9z
    prosettings: {}
    proconfig: {}
- display_names:
  - Ninjas in Pyjamas
  - NIP
  team_id: ninjas-in-pyjamas
  source_refs:
    cs2settings:
      team_slug: ninjas-in-pyjamas
    prosettings: {}
    proconfig: {}
- display_names:
  - Alliance
  team_id: alliance
  source_refs:
    cs2settings:
      team_slug: alliance
    prosettings: {}
    proconfig: {}
- display_names:
  - paiN
  team_id: pain
  source_refs:
    cs2settings:
      team_slug: pain
    prosettings: {}
    proconfig: {}
- display_names:
  - Lynn Vision
  team_id: lynn-vision
  source_refs:
    cs2settings:
      team_slug: lynn-vision
    prosettings: {}
    proconfig: {}
- display_names:
  - 100 Thieves
  team_id: 100-thieves
  source_refs:
    cs2settings:
      team_slug: 100-thieves
    prosettings: {}
    proconfig: {}
- display_names:
  - TyLoo
  team_id: tyloo
  source_refs:
    cs2settings:
      team_slug: tyloo
    prosettings: {}
    proconfig: {}
- display_names:
  - BC.Game
  team_id: bc-game
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - Legacy
  team_id: legacy
  source_refs:
    cs2settings:
      team_slug: legacy
    prosettings: {}
    proconfig: {}
- display_names:
  - EYEBALLERS
  team_id: eyeballers
  source_refs:
    cs2settings:
      team_slug: eyeballers
    prosettings: {}
    proconfig: {}
- display_names:
  - M80
  team_id: m80
  source_refs:
    cs2settings:
      team_slug: m80
    prosettings: {}
    proconfig: {}
- display_names:
  - Rare Atom
  team_id: rare-atom
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - FlyQuest
  team_id: flyquest
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - Aurora
  team_id: aurora
  source_refs:
    cs2settings:
      team_slug: aurora
    prosettings: {}
    proconfig: {}
- display_names:
  - Fnatic
  team_id: fnatic
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - BIG
  team_id: big
  source_refs:
    cs2settings:
      team_slug: big
    prosettings: {}
    proconfig: {}
- display_names:
  - OG
  team_id: og
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - Imperial
  team_id: imperial
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - Passion UA
  team_id: passion-ua
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - Gentle Mates
  team_id: gentle-mates
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - NRG
  team_id: nrg
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
- display_names:
  - Inner Circle
  team_id: inner-circle
  source_refs:
    cs2settings:
      team_slug: inner-circle
    prosettings: {}
    proconfig: {}
- display_names:
  - HOTU
  team_id: hotu
  source_refs:
    cs2settings:
      team_slug: hotu
    prosettings: {}
    proconfig: {}
- display_names:
  - DENDELE
  team_id: dendele
  source_refs:
    cs2settings:
      team_slug: dendele
    prosettings: {}
    proconfig: {}
- display_names:
  - magic
  team_id: magic
  source_refs:
    cs2settings:
      team_slug: magic
    prosettings: {}
    proconfig: {}
- display_names:
  - Luminosity
  team_id: luminosity
  source_refs:
    cs2settings:
      team_slug: null
    prosettings: {}
    proconfig: {}
